spring.application.name=demoSpring

# =========================================================
# 1. DATABASE CONFIGURATION (MYSQL)
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/coche_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=TinhBa1826@@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# 2. SERVER & SECURITY (JWT)
# =========================================================
server.port=8081
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
jwt.secret=your_jwt_secret_key
jwt.expiration=3600000

# =========================================================
# 3. GMAIL SMTP
# =========================================================
email.address=duonganhdn2000@gmail.com
email.password=zqwu gxwi bomc mfif
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email.address}
spring.mail.password=${email.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================================================
# 4. GOOGLE OAUTH
# =========================================================
spring.security.oauth2.client.registration.google.client-id=126794314021-nm62l0fhd2tua77oglb69dpco2m5a55d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# =========================================================
# 5. FACEBOOK OAUTH
# =========================================================
spring.security.oauth2.client.registration.facebook.client-id=800356243105336
spring.security.oauth2.client.registration.facebook.client-secret=8d62a40cc464f1efd04b90974454cb49
spring.security.oauth2.client.registration.facebook.scope=public_profile

# =========================================================
# 6. FIREBASE AUTHENTICATION
# =========================================================
firebase.api_key=AIzaSyC5mqx0tUP4KUIC9ST1MVf-SIkHOL5vb1M

# =========================================================
# 7. GOOGLE GEMINI API
# =========================================================
gemini.api_key=AIzaSyDC-D6IFA9G06yDwO4WRd9gIWBqN_vEmS4